### ISSUE TITLE
Custom songs are not directional

### ISSUE THREAD

**Issue by ChromaPIE** [auxves/disco#6]
Disco-driven discs cannot play directional sound as vanilla discs/discs from other mods, don't have range limit, and don't take post-process like reverb/lowpass from Sound Physics Remastered mod. It just sounds like I'm playing music on external apps. I don't know if it's able to be fixed though.

Non-disco-driven ones worked perfectly both inside jukeboxe and Vibe.

**Comment by auxves** [comment]
Make sure your ogg sound files only have one audio channel. You can use a website like [this one](https://convertio.co/mp3-ogg), making sure that the audio channels option is set to `Mono (1.0)`.

**Comment by ChromaPIE** [comment]
> Make sure your ogg sound files only have one audio channel. You can use a website like [this one](https://convertio.co/mp3-ogg), making sure that the audio channels option is set to `Mono (1.0)`.

Thanks I'll try it right away. Beside that here's another problem which I should've report to the Vibe's repo but Imma put it here: Voiding Vibe (using the Delete Item slot on the creative tab. haven't try any other ways) doesn't stop the sound.
