### ISSUE TITLE
Music discs don't work

### ISSUE THREAD

**Issue by BowBoy1** [auxves/disco#7]
I used the generator to create a new music disc. The disc is successfully pulled from the inventory but does not appear inside the jukebox and plays no audio.

**Comment by BowBoy1** [comment]
1.20.1 btw

**Comment by zzx-zEtYA** [comment]
Does not work for me either :(
The same symptoms, the added disc items exists and everything, and upon interaction with jukebox, item is consumed (won't be consumed in creative mode, as expected), but nothing happens beyond - no text or music, and cannot retrieve the disc (treated as if nothing is inside the jukebox)
Tested it with a minimized version of my instance to test and does not work either, the mod list goes as follows:
-quilt loader 0.23.1
-quilted fabric API (qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1)
---also tested with fabric-api-0.89.0+1.20.1
-disco-2.0.8
-addon pack created with the website including 1 disc
I haven't tested with fabric loader however
Included is this mentioned test addon pack just in case:
[lalala-test-1.zip](https://github.com/auxves/disco/files/14251259/lalala-test-1.zip)

**Comment by Unproductivv** [comment]
> Does not work for me either :( The same symptoms, the added disc items exists and everything, and upon interaction with jukebox, item is consumed (won't be consumed in creative mode, as expected), but nothing happens beyond - no text or music, and cannot retrieve the disc (treated as if nothing is inside the jukebox) Tested it with a minimized version of my instance to test and does not work either, the mod list goes as follows: -quilt loader 0.23.1 -quilted fabric API (qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1) ---also tested with fabric-api-0.89.0+1.20.1 -disco-2.0.8 -addon pack created with the website including 1 disc I haven't tested with fabric loader however Included is this mentioned test addon pack just in case: [lalala-test-1.zip](https://github.com/auxves/disco/files/14251259/lalala-test-1.zip)

Was the music file added in .ogg format?

**Comment by zzx-zEtYA** [comment]
yep, it is .ogg, single mono channel as advised in the page

**Comment by auxves** [comment]
Sorry y'all this is really late but I fixed it 😭 It wasn't an issue with the mod, but with the generator.

**Comment by zzx-zEtYA** [comment]
:O thank you! been a while but don't worry
